### ISSUE TITLE
Script needed: Read housekeeping with no frames running

### ISSUE THREAD

**Issue by ebokhour** [TESScience/FPE#10]
This script should obtain a full set of housekeeping data and output them in a standard format, in engineering units.  This script is intended to capture HK data without any frames running.  The output values should be compared to a reference set.

Note: This script will be used for Bring-Up and Functional testing of the FPE boards, thus it will be run in situations where the Interface Board is not mated with any other boards, and when only the Driver board is mated, and when all three boards in the stack are mated together.  We should consider providing three reference sets of HK data to cover all three cases.  There may be other cases, too, not yet defined.

**Comment by xcthulhu** [comment]
Done
