### ISSUE TITLE
Script needed: Check the variance of the HK data

### ISSUE THREAD

**Issue by ebokhour** [TESScience/FPE#13]
This script should capture 100 sets of housekeeping data and calculate the variance of the data.  The intent is to demonstrate the stability/noise levels of the HK data over a substantial data set.  Output values should be given in root variance (engineering units), and compared to a set of reference values or tolerances.  Ideally this script should be capable of running with frames running as well as when they are not, so that the difference in variance can be examined.

**Comment by ebokhour** [comment]
A functioning version of this exists as an iPython notebook on GitHub at https://github.com/TESScience/FPE_Test_Procedures/blob/master/HK_Variance.ipynb

**Comment by ebokhour** [comment]
A rough draft of this (with frames running) exists as an iPython notebook at
https://github.com/TESScience/FPE_Test_Procedures/blob/master/HK_Variance_Frames_Running.ipynb

Not sure at all if it works.

**Comment by xcthulhu** [comment]
Variance is an unusual statistic, we are now gathering standard deviation data
