### ISSUE TITLE
Documentation comment #1

### ISSUE THREAD

**Issue by ebokhour** [TESScience/FPE#23]
In the CLI tessfpe Tools tutorial, the following issues arise:
1) The "source FPE/testsuite/venv/bin/activate" command returns the following error (when run from the directory containing FPE):
Badly placed ()'s.
2) When reinstalling software, the make command does not run from within the FPE repo.  I think there should be a "cd .." command preceding it, so it runs from the directory containing FPE.

**Comment by xcthulhu** [comment]
What shell are you using?

If you are using csh, you have to run

". FPE/testsuite/venv/bin/activate.csh"

> 2) When reinstalling software, the make command does not run from within the FPE repo. I think there should be a "cd .." command preceding it, so it runs from the directory containing FPE.

This is confusing... can you write what you think the commands should be?

**Comment by ebokhour** [comment]
(1) The caladan terminals come up in tcsh.  I tried to run ". FPE/testsuite/venv/bin/activate.csh" from inside the FPE repo, but I get a "Permission denied" error.

(2) You had a section in the CLI tessfpe Tools tutorial in which you describe what to do when updating the FPE repo, or "reinstalling software".    I can't find that tutorial any more, but I was suggesting adding the "cd .." command just before the "make -C..." command (the 'make' being the last step in the process).

**Comment by xcthulhu** [comment]
Okay, the correct syntax is `source FPE/testsuite/venv/bin/activate.csh`

**Comment by ebokhour** [comment]
Yes, that works.  So from that point on, the user sees a "[venv] machinename%" prompt on the command line.

**Comment by ebokhour** [comment]
Regarding (2)  In the wiki CLI tessfpe Tools tutorial, it's the instructions
cd FPE
git pull origin master
rm -rf setup.py testsuite/venv
make -C FPE install_testsuite

which I think should be

cd FPE
git pull origin master
rm -rf setup.py testsuite/venv
cd ..
make -C FPE install_testsuite

**Comment by xcthulhu** [comment]
Okay, I have just created a `make reinstall` command in the `testsuite` directory.

Can I close this?

**Comment by ebokhour** [comment]
Yep.
