### ISSUE TITLE
Sequencer and MemFile Tool

### ISSUE THREAD

**Issue by ebokhour** [TESScience/FPE#26]
Finalize the software tool which generates files for the sequencer, program, DAC, and HK memories.  
Question: Are register memory files created with this tool?  If not, then how are those generated and config controlled?

**Comment by xcthulhu** [comment]
I don't want users to upload these files themselves, they can easily break the system and require a reset if they screw this up.  Especially if they try loading the wrapper twice.

I am not going to provide these tools for now.
