### ISSUE TITLE
Script needed: Load Wrapper

### ISSUE THREAD

**Issue by ebokhour** [TESScience/FPE#9]
Need a script which loads a specified version of the FPE FPGA Wrapper (e.g. 1.6.2 or 1.6t.5).  The script should also check a few supply voltages to verify proper loading.  It should also load the default set of operating parameters.

**Comment by ebokhour** [comment]
We have a working draft of this script on Caladan, called load_wrapper.py.  It's located in the fpe_tessting repository, which has not yet been sync'd with the upstream repository.

**Comment by xcthulhu** [comment]
This is done in the following script: https://github.com/TESScience/FPE/blob/master/scripts/load_wrapper
